### ISSUE TITLE
Failed to create the admin account in NGINX Controller

### ISSUE THREAD

**Issue by mashoodakram** [nginxinc/ansible-role-nginx-controller-install#27]
### Describe the bug
We are seeing error running below task;
TASK [nginxinc.nginx_controller.nginx_controller_install : Controller - Installing]
The pipeline is failing with error connection timed out and then Failed to create the admin account in NGING Controller.

### To reproduce
1. Deploy NGINX Controller Install role using playbook deploy.nginx.yml 

```
roles:
    - role: nginx_controller_install
      vars:
        - nginx_controller_tarball: "/tmp/controller-installer-3.15.0.tar.gz"
        - nginx_controller_install_path: /home/vmadmin
        - nginx_controller_remote_source: no
        - nginx_controller_bundled_db: true
       # - nginx_controller_db_host: 
       # - nginx_controller_db_user: ""
       # - nginx_controller_db_password: ""
        - nginx_controller_db_enable_ssl: false
        - nginx_controller_db_client_cert: 
        - nginx_controller_db_client_key: 
        - nginx_controller_db_ca: 
        - nginx_controller_tsdb_volume_type: local
        # - nginx_controller_tsdb_nfs_path: ""
        # - nginx_controller_tsdb_nfs_host: 
        - nginx_controller_smtp_host: "localhost"
        - nginx_controller_smtp_authentication: false
        - nginx_controller_smtp_use_tls: false
        - nginx_controller_noreply_address: "noreply@example.com"
        - nginx_controller_fqdn: nginx-controller2-dev.azure.defra.cloud
        - nginx_controller_organization_name: "Defra"
        - nginx_controller_admin_firstname: "Nginx"
        - nginx_controller_admin_lastname: "Defra"
        - nginx_controller_admin_email: "nginxadmin@defra.gov.uk"
        - nginx_controller_admin_password: ""
        - nginx_controller_self_signed_cert: false
        - nginx_controller_apigw_cert: /etc/ssl/certs/star_azure_defra_cloud.crt
        - nginx_controller_apigw_key: /etc/ssl/private/star_azure_defra_cloud.key
        - nginx_controller_overwrite_existing_configs: true
        - ansible_python_interpreter: /usr/bin/python3
        # - ansible_become_password: '<some secure password>'
```

       
  
We are seeing below error running controller_install role and cannot see where it's failing. Not sure if the first issue connection timed out is causing the second command to fail, using bundled db for install.

`16. Running database initialization task...\n\u001b[0m\u001b[32m NGINX Controller database has been initialized.\n\u001b[0msudo: unable to resolve host SECNGXCTLSR1003: Resource temporarily unavailable\ndb connection timed out\n\u001b[31m Failed to create the admin account in NGINX Controller.\n Detailed information can be found in installation logs at /var/log/nginx-controller/failure. Retry NGINX Controller installation or contact support, providing all logs.`

Are there any known issues with below version for controller install? Could you please provide some direction to debug the above error, happy to provide logs as required.

collections:

```
- name: nginxinc.nginx_controller
  #version: 3.3.
```
  
### Expected behaviour
Connect to database installed on same host install script is running not expecting any communication issues. 

### Your environment:
```
controller-installer-3.15.0.tar.gz
remote controller Ubuntu 18.04.5 LTS

ansible [core 2.11.4]
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/vmadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
ansible collection location = /home/vmadmin/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/local/bin/ansible
python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
jinja version = 2.10
libyaml = True
```
